services:
  postgres:
    restart: unless-stopped

  backend:
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  frontend:
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  nginx:
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
